#!/usr/bin/env node

import esbuild from 'esbuild';
import coffeeScriptPlugin from 'esbuild-coffeescript';

import fs from 'fs';
const pkg = JSON.parse(fs.readFileSync(process.env.npm_package_json, 'utf8'));

const NAME = pkg.name;
const AUTHOR = pkg.author;
const CONTRIBUTORS = pkg.contributors;
const LICENSE = pkg.license;
const VERSION = pkg.version;

const buildOptions = {
  entryPoints: ['ts.coffee'],
  bundle: true,
  plugins: [coffeeScriptPlugin()],
  platform: 'browser',
  target: ["es6"],
  banner: {
    js: `// ${NAME} - version ${VERSION}\n` +
        `//\n` +
        `// Copyright 2012 ${CONTRIBUTORS.join(', ')}\n` +
        `//\n` +
        `// ${LICENSE} License`
  }
};

esbuild.build({ ...buildOptions, ...{ format: 'esm', outfile: 'build/ts.mjs' } });
esbuild.build({ ...buildOptions, ...{ format: 'iife', globalName: '$ts', outfile: 'build/ts.js', sourcemap: true } });
esbuild.build({ ...buildOptions, ...{ format: 'iife', globalName: '$ts', outfile: 'build/ts.min.js', minify: true } });
